name: Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup jdk
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Set current directory as a safe repository
      run: git config --global --add safe.directory /github/workspace
    - uses: geertvdc/setup-hub@master
    - name: Release using hub
      run: hub release create -a ./app/build/outputs/apk/release/**.apk -m "v${GITHUB_REF##*/}" ${GITHUB_REF##*/}
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
