name: Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup jdk
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Load keystore
      run: |
        echo $GRADLE_USER_HOME && \
        mkdir -p ~/.gradle && \
        echo "${{ secrets.KEYSTORE_FILE_CONTENTS }}" | base64 -d > ~/.gradle/keystore && \
        cat <<EOL > ~/.gradle/gradle.properties
        RELEASE_STORE_FILE=~/.gradle/keystore
        RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}
        EOL
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Set current directory as a safe repository
      run: git config --global --add safe.directory /github/workspace
    - uses: ButterCam/setup-github-cli@master
    - name: Release using github cli
      run: gh release create ${GITHUB_REF##*/} ./app/build/outputs/apk/release/**.apk
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
